import { DataInput } from "@/components/definitions";

export const defaultDataInput: DataInput = {
    player: "焚影圣诀",
    delayNetwork: 45,
    delayKeyboard: 20,
    fightTime: 300,
    fightCount: 100,
    attribute: {
        method: "从数据导入",
        data: {
            Vitality: 0,
            Strength: 0,
            Agility: 0,
            Spirit: 0,
            Spunk: 0,
            PhysicsAttackPowerBase: 0,
            SolarAttackPowerBase: 0,
            LunarAttackPowerBase: 0,
            NeutralAttackPowerBase: 0,
            PoisonAttackPowerBase: 0,
            PhysicsCriticalStrike: 0,
            SolarCriticalStrike: 0,
            LunarCriticalStrike: 0,
            NeutralCriticalStrike: 0,
            PoisonCriticalStrike: 0,
            PhysicsCriticalDamagePower: 0,
            SolarCriticalDamagePower: 0,
            LunarCriticalDamagePower: 0,
            NeutralCriticalDamagePower: 0,
            PoisonCriticalDamagePower: 0,
            PhysicsOvercomeBase: 0,
            SolarOvercomeBase: 0,
            LunarOvercomeBase: 0,
            NeutralOvercomeBase: 0,
            PoisonOvercomeBase: 0,
            SurplusValue: 0,
            Strain: 0,
            Haste: 0,
            MeleeWeaponDamage: 0,
            MeleeWeaponDamageRand: 0,
            MeleeWeaponDamageMax: 0,
        },
    },
    effects: ["大附魔·腰", "大附魔·腕", "大附魔·鞋", "家园酒·加速", "套装·技能", "套装·特效"],
};
